version: "2"
services:
  app:
    build: ./app
    container_name: "Flask_App4"
    ports:
      - "5000:5000"
  app2:
    build: ./flask-jinja-tutorial/flask-jinja-tutorial
    container_name: "Flask_App6"
    ports:
      - "5001:5001"
  app3:
    build: ./flask-wtforms-tutorial/flask-wtforms-tutorial
    container_name: "Flask_App_8"
    ports:
      - "5002:5002"